using System.Text.Json;
using System.Text.Json.Nodes;
using ComfyBridge.Application.Contracts;
using ComfyBridge.Application.Models;
using ComfyBridge.Domain.Exceptions;
using ComfyBridge.Domain.Models;

namespace ComfyBridge.Application.Services;

public sealed class WorkflowAnalyzerService(IAiClient aiClient) : IWorkflowAnalyzer
{
    public async Task<WorkflowAnalysisResult> AnalyzeAsync(string workflowJson, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(workflowJson))
        {
            throw new InputValidationException("Workflow JSON is required.");
        }

        JsonElement root;
        try
        {
            using var document = JsonDocument.Parse(workflowJson);
            root = document.RootElement.Clone();
        }
        catch (JsonException ex)
        {
            throw new InputValidationException($"Workflow JSON is invalid: {ex.Message}");
        }

        if (root.ValueKind != JsonValueKind.Object)
        {
            throw new InputValidationException("Workflow JSON must be an object.");
        }

        var detectedNodeTypes = DetectNodeTypes(root);

        TemplateDefinition template;
        var notes = new List<string>();

        try
        {
            template = await aiClient.AnalyzeWorkflowAsync(workflowJson, cancellationToken);
            notes.Add("Mapping generated by AI.");
        }
        catch (Exception ex)
        {
            notes.Add($"AI mapping failed: {ex.Message}. No mapping applied.");
            var emptyExample = new JsonObject { ["template"] = "workflow:1.0", ["inputs"] = new JsonObject() };
            template = new TemplateDefinition
            {
                Name = "workflow",
                Version = "1.0",
                Inputs = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase),
                Mapping = new Dictionary<string, WorkflowInputMapping>(StringComparer.OrdinalIgnoreCase),
                ExampleRequest = emptyExample
            };
        }

        notes.AddRange(detectedNodeTypes
            .OrderBy(t => t, StringComparer.OrdinalIgnoreCase)
            .Select(t => $"Detected node: {t}"));

        return new WorkflowAnalysisResult
        {
            WorkflowJson = workflowJson,
            Template = template,
            ExampleRequest = (JsonObject)template.ExampleRequest.DeepClone(),
            DetectedNodeTypes = detectedNodeTypes.OrderBy(x => x, StringComparer.OrdinalIgnoreCase).ToArray(),
            Notes = notes
            };
    }

        private static HashSet<string> DetectNodeTypes(JsonElement root)
        {
            var nodeTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var property in root.EnumerateObject())
            {
                if (property.Value.ValueKind != JsonValueKind.Object)
                    continue;
                if (property.Value.TryGetProperty("class_type", out var ct) && ct.ValueKind == JsonValueKind.String)
                {
                    var value = ct.GetString();
                    if (!string.IsNullOrWhiteSpace(value))
                        nodeTypes.Add(value);
                }
            }
            return nodeTypes;
        }
}